### ISSUE TITLE
Don't allow installing packages that are already installed as a direct blazorrepl dependency

### ISSUE THREAD

**Issue by KristianMariyanov** [BlazorRepl/BlazorRepl#115]
We are currently disabling buttons for the packages that the user is installed. But we should disable the button for the packages that we have preinstalled in the platform.

**Comment by vladislav-karamfilov** [comment]
Done in https://github.com/BlazorRepl/BlazorRepl/commit/aab606760f5876525fc741aa3bb47115086074a9

**Comment by vladislav-karamfilov** [comment]
We actually load only the popular package subset of all packages/assemblies that are installed/referenced to Blazor REPL app.

**Comment by vladislav-karamfilov** [comment]
The UI part of the issue is separated into #119
