### ISSUE TITLE
Save not working currently

### ISSUE THREAD

**Issue by SQL-MisterMagoo** [BlazorRepl/BlazorRepl#41]
The url https://snippets.blazorrepl.com/ is returning a 400
Save is not working

**Comment by KristianMariyanov** [comment]
Hello @SQL-MisterMagoo, 

Are you trying to create a snippet trough https://blazorrepl.com?
Please note that we are currently not supporting creating snippets trough API or different than https://blazorrepl.com domains.

**Comment by SQL-MisterMagoo** [comment]
Hi, no just using the save button on the website

**Comment by KristianMariyanov** [comment]
Can you please share the code of the snippet you are trying to save, so we could reproduce it and investigate further. Maybe there is some validation error.

**Comment by SQL-MisterMagoo** [comment]
I'm not even putting any specific code in - just navigate to the site, click Save and then Confirm - the Blazor error UI shows up and the dev tools show that the server returned a 400 code for that snippets url.

**Comment by SQL-MisterMagoo** [comment]
This is the response for that request from the network tab of dev tools:

```
access-control-allow-headers: Content-Type
access-control-allow-methods: HEAD, POST, OPTIONS
access-control-allow-origin: *
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
cf-ray: 5be0f6837f220079-LHR
cf-request-id: 046078662e000000799094e200000001
content-length: 0
date: Wed, 05 Aug 2020 13:46:12 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
set-cookie: __cfduid=d37040f17020dd5825ab750eff0558b491596635172; expires=Fri, 04-Sep-20 13:46:12 GMT; path=/; domain=.blazorrepl.com; HttpOnly; SameSite=Lax; Secure
status: 400
vary: Accept-Encoding
```

**Comment by vladislav-karamfilov** [comment]
@SQL-MisterMagoo , thanks for bringing this to our attention! We will certainly deeply investigate this. We have some more questions. How much it takes to get a response from the server? Does it return the client error response code immediately or after some time? And if it after time can you please provide us what the time interval is?

**Comment by SQL-MisterMagoo** [comment]
The initial response is 22ms for the site as a whole - the complete load time for the home page is 2.62 seconds.
The requests that error take about 20ms to 30ms total from initial request to repsonse.

**Comment by vladislav-karamfilov** [comment]
These are good times! How much time the specific create snippet request-response take? You can view this info in the Network tab of dev tools.

**Comment by SQL-MisterMagoo** [comment]
That was around 20ms - response was a 400 code from cloudflare

**Comment by vladislav-karamfilov** [comment]
Hmm, timeout was our first lead to finding the root cause of this but it's perfect time so this is not the reason. We are trying to break it but without any success so far. If that's not an issue for you, can you please extract from dev tools the raw request headers and request body? Hopefully, this will give us all details we need to reproducing the issue and providing a working solution. Thank you very much in advance!

**Comment by SQL-MisterMagoo** [comment]
I will, but later as I'm just going out. Maybe it's a GitHub
pages/Cloudflare issue rather than yours?

**Comment by vladislav-karamfilov** [comment]
We use GitHub Pages only for static files server so it won't be GH Pages but it might be something on CloudFlare. The strange thing is it's working fine from all locations that we test on.

**Comment by SQL-MisterMagoo** [comment]
I just tried it on some other browsers - looks like it is just Edge Dev that is experiencing this issue

Version 86.0.587.0 (Official build) dev (64-bit)

I will close the issue as it appears

**Comment by vladislav-karamfilov** [comment]
Hey @SQL-MisterMagoo , we are glad that you find your way to successfully using our platform! However we target on supporting Edge browser and we will be very thankful if you get the chance on providing us request headers and body with which the request fails. Thank you again! :)

**Comment by SQL-MisterMagoo** [comment]
Sure - I just wouldn't want you wasting time on a DEV branch issue...

This is the request that **fails** in Edge DEV branch Version 86.0.587.0 (Official build) dev (64-bit)
```
fetch("https://snippets.blazorrepl.com/", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-GB,en;q=0.9,fr;q=0.8,en-US;q=0.7",
    "cache-control": "no-cache",
    "content-type": "application/json; charset=utf-8",
    "pragma": "no-cache",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-site"
  },
  "referrer": "https://blazorrepl.com/",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"files\":[{\"path\":null,\"content\":\"\\u003Ch1\\u003EHello World\\u003C/h1\\u003E\\n\\n@code {\\n\\n}\\n\"}]}",
  "method": "POST",
  "mode": "cors",
  "credentials": "omit"
});
```

And the same request **working** in Edge stable Version 84.0.522.52 (Official build) (64-bit)
```
fetch("https://snippets.blazorrepl.com/", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-GB,en;q=0.9,en-US;q=0.8",
    "content-type": "application/json; charset=utf-8",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-site"
  },
  "referrer": "https://blazorrepl.com/repl",
  "referrerPolicy": "no-referrer-when-downgrade",
  "body": "{\"files\":[{\"path\":null,\"content\":\"\\u003Ch1\\u003EHello World\\u003C/h1\\u003E\\n\\n@code {\\n\\n}\\n\"}]}",
  "method": "POST",
  "mode": "cors",
  "credentials": "omit"
});
```

**Comment by SQL-MisterMagoo** [comment]
I think I have identified the cause - the flag "Reduce default 'referer' header granularity." appears to **enabled** by default.
Switching it to **disabled** solves this issue for me.

![image](https://user-images.githubusercontent.com/11338430/89435742-30355580-d73d-11ea-9563-14c7529345e4.png)

**Comment by vladislav-karamfilov** [comment]
Hey @SQL-MisterMagoo , this is extremely helpful! We do use this header for validation when creating snippets but we never thought browsers will have it non-standard-compliant populated. We will take the necessary steps to prevent this being an issue for all users. Thank you very much for your time and collaboration during this investigation! 🙏

**Comment by vladislav-karamfilov** [comment]
We made the necessary adjustments to support this future browser feature and users won't face issues with this anymore.

**Comment by SQL-MisterMagoo** [comment]
I just got an update of Edge Dev to Version 86.0.594.1 (Official build) dev (64-bit) and can confirm BlazorRepl is working on the default settings and with that setting enabled.
Good work!
