### ISSUE TITLE
Clear down user page / results / run window

### ISSUE THREAD

**Issue by SQL-MisterMagoo** [BlazorRepl/BlazorRepl#44]
When you jump to a saved repl, the right hand pane that shows the running sample should be cleared as it currently shows the output from your last repl

e.g. Navigate here : https://blazorrepl.com/repl/GYaCaqai51KSzLfy46
and run it - you will see the output 
## My Previous Repl

Now, navigate to here : https://blazorrepl.com/repl/wEkhGJkE5860Qg1K55
Before you run, you still see 
## My Previous Repl 
This is misleading - could you clear the right hand frame when you fetch the repl?

**Comment by KristianMariyanov** [comment]
Hey @SQL-MisterMagoo, thanks for reporting this to us! 

We agree that this behaviour is a bit misleading. The approach you are suggestion is great.
We discussed one more approach to this problem which will automatically run the code snippet and render the result.
Although it will be strange to enter the link from StackOverflow and wait additional few seconds to compile and render the code, tho

What approach you as a user would you prefer?

Thanks again for your time and we hope Blazor REPL meets your expectations and is useful to you! :)

**Comment by SQL-MisterMagoo** [comment]
I would personally prefer a standard page with instructions on how to run
the repl
