### ISSUE TITLE
Add more descriptive instructions as a default user component page

### ISSUE THREAD

**Issue by KristianMariyanov** [BlazorRepl/BlazorRepl#46]
Currently we visualize this: 
![image](https://user-images.githubusercontent.com/6886919/89565715-a4e4be80-d827-11ea-88e7-a4679fbfd129.png)

We want to improve the instructions.

- Add Ctrl + S
- Add a description about save
- Add description about the editor

**Comment by YanaSlavcheva** [comment]
Taking this one
