### ISSUE TITLE
Compilation Service Refactoring

### ISSUE THREAD

**Issue by KristianMariyanov** [BlazorRepl/BlazorRepl#5]
- Remove unused code - DONE
- Optimize existing code - DONE
- Improve exception handling - DONE
- Remove warning for duplicate namespace usings - DONE
- Optimize `CompilationService` initialization - Remove static methods and use IoC

**Comment by vladislav-karamfilov** [comment]
All done after PR #114 is merged now.

**Comment by vladislav-karamfilov** [comment]
https://github.com/BlazorRepl/BlazorRepl/commit/5561836e85bc902bf0976b0b79bc68ec65946068
