### ISSUE TITLE
Revisit all public component properties and methods

### ISSUE THREAD

**Issue by vladislav-karamfilov** [BlazorRepl/BlazorRepl#56]
Currently we have a lot of public component props and methods but many of them should be private. We should revisit all components and make the necessary changes.

 Here is an example from `ErrorList` component:
https://github.com/BlazorRepl/BlazorRepl/blob/5c7f061eb9cc75ac1121d70ba9f4828e9eb465c1/Client/Components/ErrorList.razor.cs#L22-L32

All of these properties and methods can be `private`

**Comment by YanaSlavcheva** [comment]
@vladislav-karamfilov @KristianMariyanov I am taking this one

**Comment by vladislav-karamfilov** [comment]
Closed by #81
