### ISSUE TITLE
Add confirm when user leaves/reloads

### ISSUE THREAD

**Issue by KristianMariyanov** [BlazorRepl/BlazorRepl#68]
Currently, when a user writes some code in the editor and accidentally refresh or leave the page all the code is lost. 

We want to add a confirm prompt which will notify the user that all the progress will be lost.

The feature is applicable only in the `/repl` page

**Comment by 1880akshay** [comment]
Hey @KristianMariyanov I can work on this issue if you may tell how to add some javascript code only to a particular route (in this case /repl )

**Comment by KristianMariyanov** [comment]
I believe the best way will be to add the handler on the first render of the Repl component and remove it on `Dispose`

Unfortunately, Blazor doesn't support JS isolation yet.

**Comment by vladislav-karamfilov** [comment]
Hey, @1880akshay ! Thanks for taking the time to play with Blazor REPL!

Please, do not hesitate to ask us anything related to this issue if you are still having interest on contributing it.

**Comment by 1880akshay** [comment]
hey @vladislav-karamfilov , actually I am new to Blazor and still learning syntax and exploring it a bit due to which I wont be able to contribute as of now. Sorry for the inconvenience.

**Comment by vladislav-karamfilov** [comment]
> hey @vladislav-karamfilov , actually I am new to Blazor and still learning syntax and exploring it a bit due to which I wont be able to contribute as of now. Sorry for the inconvenience.

No problem, @1880akshay! Good luck and have fun with Blazor!

**Comment by SQL-MisterMagoo** [comment]
Just lost a nice demo because of this 🤦🏼‍♂️

There is a tiny gap between the "Blazor REPL" button and the _Main.razor tab - and I missed _Main.razor and accidentally clicked Blazor REPL.

![image](https://user-images.githubusercontent.com/11338430/100300623-5a31b280-2f8e-11eb-8276-e4f326ef2453.png)

**Comment by vladislav-karamfilov** [comment]
> Just lost a nice demo because of this 🤦🏼‍♂️
> 
> There is a tiny gap between the "Blazor REPL" button and the _Main.razor tab - and I missed _Main.razor and accidentally clicked Blazor REPL.
> 
> ![image](https://user-images.githubusercontent.com/11338430/100300623-5a31b280-2f8e-11eb-8276-e4f326ef2453.png)

Hey @SQL-MisterMagoo ! Sorry to hear that happened... It bothered us a couple of times too so we implemented this feature now. When the user reloads the page or leaves the site or navigates away from the REPL page, he/she will be prompted to confirm that. Unfortunately, we didn't find any way of handling this for browser's back/forward buttons and left it for another time (#79). We'll deploy this feature until the end of the day.

**Comment by SQL-MisterMagoo** [comment]
Thank you a million times! So good!
