### ISSUE TITLE
Radzen Nuget package doesnt work

### ISSUE THREAD

**Issue by ashishsinha24** [BlazorRepl/BlazorRepl#91]
Hi,
Congratulations on this achievement. 
How can I make it work with Radzen Blazor?

**Comment by vladislav-karamfilov** [comment]
Hey, @ashishsinha24! Thanks for checking out our latest release. Here is a snippet that we prepared for you that you can start from for building components using Radzen Blazor: https://blazorrepl.com/repl/GlEcPhmv53oICePr39. We hope that this will help you.

**Comment by ashishsinha24** [comment]
Thanks. It works nicely but there is a small glitch. It only works for the first time.
I mean I have to refresh the snippet to retest something new

**Comment by vladislav-karamfilov** [comment]
Hey, @ashishsinha24! We have fixed this issue and all should be OK now. Please try again and write us back.

**Comment by ashishsinha24** [comment]
Thanks, for the quick update. Yes its working 
but how can I add the radzen css to it.
[https://blazorrepl.com/repl/GlEcPhmv53oICePr39](url)

**Comment by vladislav-karamfilov** [comment]
Glad to hear everything is working fine now.

About the CSS: we are currently loading all CSS and JS files to the result app but we plan to have this feature of letting users define which static assets in a package they want to load in their apps. This is of high priority for us too.

**Comment by vladislav-karamfilov** [comment]
Hey @ashishsinha24! We now support enabling/disabling of static assets that come from NuGet packages. Here is a snippet that's based on your snippet with the humanistic theme of Radzen: https://blazorrepl.com/repl/wbkHmOlo18RcV7va29.

Closing this issue now but feel free to reopen it if you have any additional questions.
