### ISSUE TITLE
Allow upgrade of already installed package dependencies

### ISSUE THREAD

**Issue by KristianMariyanov** [BlazorRepl/BlazorRepl#99]
Steps to reproduce
Currently, if we install package A with a dependency version of Package B - 1.2.0, then install package C with a dependency to the same package B, but higher version - for example 1.3.0, we are throwing `InvalidOperationException`

The correct thing is to go to the already installed package A and check if we the new version (1.3.0) will fit its version constrains, if it does, we can remove the package B  version 1.2 and add only the new version.

We shouldn't allow updating the version of packages that are not dependencies (directly installed from the package manager)

We should think about can we upgrade the version of our internal package dependencies.

**Comment by vladislav-karamfilov** [comment]
> We should think about can we upgrade the version of our internal package dependencies.

We decided that this is not something that we want to support.
